steps:
  # Step 1: Configure gcloud as the credential helper for Docker
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud auth configure-docker us-central1-docker.pkg.dev

  # Step 2: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/cogent-density-239117/cicd-practice-repo/my-image:$COMMIT_SHA', '.']

  # Step 3: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/cogent-density-239117/cicd-practice-repo/my-image:$COMMIT_SHA']

  # Step 4: Save the code to Source Repositories
  - name: 'gcr.io/cloud-builders/git'
    args: ['push', 'https://source.developers.google.com/p/cogent-density-239117/r/$REPO_NAME', '--all']

images:
  # Define the Docker image to push to Artifact Registry
  - 'us-central1-docker.pkg.dev/cogent-density-239117/cicd-practice-repo/my-image:$COMMIT_SHA'

substitutions:
  _REPO_NAME: cicd-practice-repo
  _BRANCH_NAME: main

options:
  logging: CLOUD_LOGGING_ONLY
